// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Pardis.WebApp.Areas.SalesManagement.Controllers
{
    public partial class NeedController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public NeedController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected NeedController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetAllNeedsByProfileId()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetAllNeedsByProfileId);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult PardisJson()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.PardisJson);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public NeedController Actions { get { return MVC.SalesManagement.Need; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "SalesManagement";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Need";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Need";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string GetAllNeedsByProfileId = "GetAllNeedsByProfileId";
            public readonly string PardisJson = "PardisJson";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string GetAllNeedsByProfileId = "GetAllNeedsByProfileId";
            public const string PardisJson = "PardisJson";
        }


        static readonly ActionParamsClass_GetAllNeedsByProfileId s_params_GetAllNeedsByProfileId = new ActionParamsClass_GetAllNeedsByProfileId();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetAllNeedsByProfileId GetAllNeedsByProfileIdParams { get { return s_params_GetAllNeedsByProfileId; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetAllNeedsByProfileId
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_PardisJson s_params_PardisJson = new ActionParamsClass_PardisJson();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PardisJson PardisJsonParams { get { return s_params_PardisJson; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PardisJson
        {
            public readonly string item = "item";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_NeedController : Pardis.WebApp.Areas.SalesManagement.Controllers.NeedController
    {
        public T4MVC_NeedController() : base(Dummy.Instance) { }

        [NonAction]
        partial void GetAllNeedsByProfileIdOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetAllNeedsByProfileId(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetAllNeedsByProfileId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GetAllNeedsByProfileIdOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void PardisJsonOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, object item);

        [NonAction]
        public override System.Web.Mvc.JsonResult PardisJson(object item)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.PardisJson);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "item", item);
            PardisJsonOverride(callInfo, item);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
