//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pardis.Product.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallForPrice
    {
        public int Id { get; set; }
        public Nullable<int> SalesFolderId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ShippingPrice { get; set; }
        public Nullable<int> SupplierProfileId { get; set; }
        public Nullable<System.DateTime> DeliveryTime { get; set; }
        public Nullable<int> SupplyTypeId { get; set; }
        public string UnitPrice { get; set; }
        public Nullable<int> PriceTypeId { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> StatusProductId { get; set; }
        public Nullable<int> ShippingPriceTypeId { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    
        public virtual Content Content { get; set; }
        public virtual Item Item { get; set; }
        public virtual Item Item1 { get; set; }
        public virtual Item Item2 { get; set; }
        public virtual Item Item3 { get; set; }
        public virtual Product Product { get; set; }
        public virtual Profile Profile { get; set; }
        public virtual SalesFolder SalesFolder { get; set; }
    }
}
