//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pardis.Product.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Content()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int Id { get; set; }
        public int ContentType { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsArchive { get; set; }
        public string Description { get; set; }
        public Nullable<int> StateKindeGroup { get; set; }
        public Nullable<int> StateKinde { get; set; }
    
        public virtual CallForPrice CallForPrice { get; set; }
        public virtual File File { get; set; }
        public virtual Need Need { get; set; }
        public virtual Product Product { get; set; }
        public virtual SalesFolder SalesFolder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
    }
}
