//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pardis.Product.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesFolder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesFolder()
        {
            this.CallForPrices = new HashSet<CallForPrice>();
            this.ProductListRelateds = new HashSet<ProductListRelated>();
        }
    
        public int Id { get; set; }
        public Nullable<int> NeedId { get; set; }
        public string Subject { get; set; }
        public Nullable<System.DateTime> PriceAnnouncementDeadline { get; set; }
        public Nullable<System.DateTime> DeliveryDeadline { get; set; }
        public Nullable<int> RequestTypeId { get; set; }
        public string WarrantyTerms { get; set; }
        public string Description { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public Nullable<int> ProcessStepId { get; set; }
        public string DescriptionLom { get; set; }
    
        public virtual Content Content { get; set; }
        public virtual Item Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallForPrice> CallForPrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductListRelated> ProductListRelateds { get; set; }
    }
}
